<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Admin · Finora</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/app.css?v=4"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/admin.css"></head><body>
<%@ include file="header.jspf" %><main class="page-shell"><%@ include file="flash.jspf" %>
    <section class="page-heading"><div><div class="eyebrow">FINORA CONTROL ROOM</div><h1>Administration</h1><p class="muted">Manage accounts, security controls, system settings, and reports.</p></div><span class="role-pill">ADMINISTRATOR</span></section>
    <section class="summary-grid admin-summary"><article class="summary-card summary-highlight"><div class="summary-label">Registered accounts</div><div class="summary-value"><c:out value="${totalAccounts}"/></div><div class="summary-foot">All platform users</div></article><article class="summary-card"><div class="summary-label">Active accounts</div><div class="summary-value"><c:out value="${activeAccounts}"/></div><div class="summary-foot"><c:out value="${inactiveAccounts}"/> disabled</div></article><article class="summary-card"><div class="summary-label">Failed sign-ins · 30 days</div><div class="summary-value"><c:out value="${failedLogins30d}"/></div><div class="summary-foot">Security incidents to review</div></article><article class="summary-card"><div class="summary-label">System events · 30 days</div><div class="summary-value"><c:out value="${securityEvents30d}"/></div><div class="summary-foot">Recorded administrative activity</div></article></section>

    <section class="panel form-panel"><div class="panel-heading"><div><div class="eyebrow">CREATE ACCOUNT</div><h2>Add a user or administrator</h2></div></div>
        <form method="post" action="${pageContext.request.contextPath}/admin" class="form-grid admin-create-form"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="create-user">
            <label>Full name<input name="name" maxlength="80" required></label><label>Email<input type="email" name="email" maxlength="160" required></label><label>Temporary password<input type="password" name="password" minlength="12" maxlength="200" required><small>At least 12 characters</small></label><label>Role<select name="role"><option value="USER">User</option><option value="ADMIN">Admin</option></select></label><div class="form-action"><button class="button button-primary" type="submit">Create account</button></div>
        </form>
    </section>

    <section class="panel"><div class="panel-heading"><div><div class="eyebrow">ACCESS CONTROL</div><h2>User accounts</h2><p class="muted panel-subtitle">Search, filter, edit profile/access, reset password, or permanently remove an account.</p></div><span class="count-pill"><c:out value="${users.size()}"/> shown · max 500</span></div>
        <form method="get" action="${pageContext.request.contextPath}/admin" class="filter-row admin-filter"><label>Search<input type="search" name="userQuery" value="<c:out value='${userQuery}'/>" placeholder="Name or email"></label><label>Role<select name="role"><option value="">All roles</option><option value="USER" ${selectedRole eq 'USER' ? 'selected' : ''}>User</option><option value="ADMIN" ${selectedRole eq 'ADMIN' ? 'selected' : ''}>Admin</option></select></label><label>Status<select name="status"><option value="">All statuses</option><option value="active" ${selectedStatus eq 'active' ? 'selected' : ''}>Active</option><option value="inactive" ${selectedStatus eq 'inactive' ? 'selected' : ''}>Disabled</option></select></label><button class="button button-secondary" type="submit">Apply filters</button><a class="text-link" href="${pageContext.request.contextPath}/admin">Clear</a></form>
        <c:choose><c:when test="${empty users}"><div class="empty-state compact"><p>No accounts match these filters.</p></div></c:when><c:otherwise><div class="table-scroll"><table class="data-table admin-users-table"><thead><tr><th>Account</th><th>Current role</th><th>Status</th><th>Created</th><th>Edit account and access</th><th>Remove</th></tr></thead><tbody>
        <c:forEach var="account" items="${users}"><tr><td><strong><c:out value="${account.name}"/></strong><span class="table-sub"><c:out value="${account.email}"/></span></td><td><span class="role-pill ${account.role eq 'ADMIN' ? 'role-admin' : ''}"><c:out value="${account.role}"/></span></td><td><span class="status-dot ${account.active ? 'status-active' : 'status-inactive'}"></span><c:choose><c:when test="${account.active}">Active</c:when><c:otherwise>Disabled</c:otherwise></c:choose></td><td><c:out value="${account.createdAt}"/></td><td><form method="post" action="${pageContext.request.contextPath}/admin" class="admin-account-form"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="update-user"><input type="hidden" name="id" value="${account.id}"><label>Name<input name="name" value="<c:out value='${account.name}'/>" maxlength="80" required></label><label>Email<input type="email" name="email" value="<c:out value='${account.email}'/>" maxlength="160" required></label><label>Role<select name="role"><option value="USER" ${account.role eq 'USER' ? 'selected' : ''}>User</option><option value="ADMIN" ${account.role eq 'ADMIN' ? 'selected' : ''}>Admin</option></select></label><label class="check-label"><input type="checkbox" name="active" ${account.active ? 'checked' : ''}> Active</label><label>Reset password<input type="password" name="password" minlength="12" maxlength="200" placeholder="Leave blank to keep"></label><button class="button button-secondary button-small" type="submit">Save changes</button></form></td><td><form method="post" action="${pageContext.request.contextPath}/admin" class="delete-account-form"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="delete-user"><input type="hidden" name="id" value="${account.id}"><label class="check-label delete-confirm"><input type="checkbox" name="confirmation" value="DELETE" required> Confirm</label><button class="button-danger-text" type="submit">Delete</button></form></td></tr></c:forEach>
        </tbody></table></div></c:otherwise></c:choose>
    </section>

    <section class="panel"><div class="panel-heading"><div><div class="eyebrow">SYSTEM SETTINGS</div><h2>Platform preferences and feature controls</h2><p class="muted panel-subtitle">Changes take effect immediately and are written to the audit report.</p></div></div>
        <form method="post" action="${pageContext.request.contextPath}/admin" class="settings-grid"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="save-settings">
            <label class="setting-toggle"><input type="checkbox" name="registration_enabled" ${registrationEnabled ? 'checked' : ''}><span><strong>Public registration</strong><small>Allow new users to create accounts.</small></span></label>
            <label class="setting-toggle"><input type="checkbox" name="maintenance_mode" ${maintenanceMode ? 'checked' : ''}><span><strong>Maintenance mode</strong><small>Pause user access while admins continue working.</small></span></label>
            <label class="setting-toggle"><input type="checkbox" name="budgets_enabled" ${budgetsEnabled ? 'checked' : ''}><span><strong>Budgets</strong><small>Enable budget creation and tracking.</small></span></label>
            <label class="setting-toggle"><input type="checkbox" name="goals_enabled" ${goalsEnabled ? 'checked' : ''}><span><strong>Financial goals</strong><small>Enable goals and progress tracking.</small></span></label>
            <label class="setting-toggle"><input type="checkbox" name="reports_enabled" ${reportsEnabled ? 'checked' : ''}><span><strong>User reports</strong><small>Show category spending charts on the user dashboard.</small></span></label>
            <div class="form-action"><button class="button button-primary" type="submit">Save all settings</button></div>
        </form>
    </section>

    <div class="content-grid admin-grid">
        <section class="panel"><div class="panel-heading"><div><div class="eyebrow">FINANCIAL DATA SECURITY</div><h2>Encryption and access controls</h2></div></div><ul class="security-list"><li><span class="security-check">✓</span><span><strong>At-rest finance encryption</strong><small><c:out value="${encryptionLabel}"/> protects expense, budget, goal, and recurring schedule details using authenticated encryption.</small></span></li><li><span class="security-check">✓</span><span><strong>Role and ownership checks</strong><small>Admins manage accounts; user finance records are scoped to the signed-in owner.</small></span></li><li><span class="security-check">✓</span><span><strong>Request protections</strong><small>PBKDF2 password hashes, CSRF tokens, prepared statements, session rotation, and security headers.</small></span></li></ul><p class="key-backup-note"><strong>Key backup:</strong> Keep a secure backup of <code><c:out value="${keyBackupPath}"/></code>. Without it, encrypted finance data cannot be recovered.</p><form method="post" action="${pageContext.request.contextPath}/admin" class="rotate-key-form"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="rotate-encryption-key"><label class="check-label"><input type="checkbox" name="confirmRotation" value="yes" required> I backed up the current key ring</label><button class="button button-secondary" type="submit">Rotate encryption key</button></form></section>
        <section class="panel"><div class="panel-heading"><div><div class="eyebrow">SECURITY AND COMPLIANCE REPORT</div><h2>Activity and incident review</h2></div><span class="count-pill">30 days</span></div><p class="muted">Review failed sign-ins, account changes, system settings, and encryption events. Filter below or export the matching report.</p><div class="report-stat-row"><div><strong><c:out value="${failedLogins30d}"/></strong><span>failed sign-ins</span></div><div><strong><c:out value="${securityEvents30d}"/></strong><span>recorded events</span></div><div><strong><c:out value="${activeAdmins}"/></strong><span>active admins</span></div></div></section>
    </div>

    <section class="panel"><div class="panel-heading"><div><div class="eyebrow">AUDIT TRAIL</div><h2>System and user activity</h2></div><span class="count-pill"><c:out value="${auditLogs.size()}"/> events shown</span></div>
        <form method="get" action="${pageContext.request.contextPath}/admin" class="filter-row audit-filter"><label>Search<input type="search" name="auditQuery" value="<c:out value='${auditQuery}'/>" placeholder="Actor, event, or details"></label><label>Event<select name="event"><option value="">All events</option><option value="LOGIN_FAILED" ${selectedEvent eq 'LOGIN_FAILED' ? 'selected' : ''}>Failed sign-ins</option><option value="LOGIN" ${selectedEvent eq 'LOGIN' ? 'selected' : ''}>Successful sign-ins</option><option value="USER_ACCOUNT_UPDATED" ${selectedEvent eq 'USER_ACCOUNT_UPDATED' ? 'selected' : ''}>Account changes</option><option value="SYSTEM_SETTINGS_UPDATED" ${selectedEvent eq 'SYSTEM_SETTINGS_UPDATED' ? 'selected' : ''}>System settings</option><option value="ENCRYPTION_KEY_ROTATED" ${selectedEvent eq 'ENCRYPTION_KEY_ROTATED' ? 'selected' : ''}>Encryption key rotations</option><option value="SYSTEM_STARTED" ${selectedEvent eq 'SYSTEM_STARTED' ? 'selected' : ''}>System starts</option></select></label><label>From<input type="date" name="from" value="${auditFrom}"></label><label>To<input type="date" name="to" value="${auditTo}"></label><button class="button button-secondary" type="submit">Filter report</button><a class="text-link" href="${pageContext.request.contextPath}/admin">Clear</a></form>
        <form method="get" action="${pageContext.request.contextPath}/admin/reports/audit.csv" class="export-form"><input type="hidden" name="auditQuery" value="<c:out value='${auditQuery}'/>"><input type="hidden" name="event" value="${selectedEvent}"><input type="hidden" name="from" value="${auditFrom}"><input type="hidden" name="to" value="${auditTo}"><button class="text-link export-link" type="submit">Download filtered CSV report ↓</button></form>
        <c:choose><c:when test="${empty auditLogs}"><div class="empty-state compact"><p>No events match these filters.</p></div></c:when><c:otherwise><div class="table-scroll"><table class="data-table audit-table"><thead><tr><th>Event</th><th>Actor</th><th>Details</th><th>Time</th></tr></thead><tbody><c:forEach var="log" items="${auditLogs}"><tr><td><span class="event-pill"><c:out value="${log.event}"/></span></td><td><c:out value="${log.actorEmail}"/></td><td><c:out value="${log.details}"/></td><td><c:out value="${log.occurredAt}"/></td></tr></c:forEach></tbody></table></div></c:otherwise></c:choose>
    </section>
    <footer class="site-footer">Finora · Administrator view</footer>
</main></body></html>
